# Generated by Django 3.1.7 on 2021-03-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210307_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
