# Generated by Django 3.1.7 on 2021-03-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210307_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='prueba', max_length=400),
            preserve_default=False,
        ),
    ]
